// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  code: __t.string().primaryKey(),
  joined: __t.bool(),
  player1State: __t.string().name("player_1_state"),
  player1Ready: __t.bool().name("player_1_ready"),
  player2State: __t.string().name("player_2_state"),
  player2Ready: __t.bool().name("player_2_ready"),
  started: __t.bool(),
  levelIndices: __t.array(__t.i16()).name("level_indices"),
  winner: __t.u8(),
});
