// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Game = __t.object("Game", {
  code: __t.string(),
  player1State: __t.string(),
  player1Ready: __t.bool(),
  player2State: __t.string(),
  player2Ready: __t.bool(),
  started: __t.bool(),
  levelIndices: __t.array(__t.i16()),
  winner: __t.u8(),
});
export type Game = __Infer<typeof Game>;

